### ISSUE TITLE
Any plans to automatically download sqlcl?

### ISSUE THREAD

**Issue by rafael-trevisan** [joeploijens/homebrew-tap#3]
Hi, nice tap and formulae! Any plans to automatically download the sqlcl?

i tried to use the alias (ln) but it didn't work. It only worked when I copied the .zip to the Homebrew folder.

**Comment by joeploijens** [comment]
Hi Rafael,

automatic download of the sqlcl software is not possible AFAIK. Oracle requires you to sign in before you can download the software.

Regarding the installation of sqlcl, both methods as described in the formula work for me. The alias (ln) or the software (zip) needs to be in the Homebrew cache folder (by default `~/Library/Caches/Homebrew`).
